---
- name: Upgrade CFME to latest version
  hosts: cfme-appliances
  remote_user: root
  tasks:
  - name: stop CFME engine (evmserverd)
    service:
      name: evmserverd
      state: stopped

  - name: Copy repo data to appliance
    yum_repository:
      name: "update-{{ item.0 }}"
      description: "CFME upgrade repo #{{ item.0 }}"
      baseurl: "{{ item.1 }}"
      gpgcheck: no
    with_indexed_items: "{{ repos }}"

  - name: Register to subscription manager
    redhat_subscription:
      state: present
      username: "{{ username }}"
      password: "{{ password }}"

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
      disable_gpg_check: yes

  - name: restart pglogical library
    service:
      name: "{{ ansible_env['APPLIANCE_PG_SERVICE'] }}"
      state: restarted

  - name: migrate everything in the database to work with the new version
    shell: |
      cd /var/www/miq/vmdb
      rake db:migrate
      exit 0
  - name: resets the ManageIQ
    shell: |
      cd /var/www/miq/vmdb
      rake evm:automate:reset
      exit 0

  - name: Restart PostgreSQL
    service:
      name: "{{ ansible_env['APPLIANCE_PG_SERVICE'] }}"
      state: restarted

  - name: start CFME engine (evmserverd)
    service:
      name: evmserverd
      state: started