---
   - name: "Wait for CFME to be avaliable"
     uri:
       url: "http://{{ansible_hostname}}"
       status_code: 200
     register: result
     until: result.status == 200
     retries: 60
     delay: 10