---
- name: restart pglogical library
  service:
    name: "{{ ansible_env['APPLIANCE_PG_SERVICE'] }}"
    state: restarted

- name: migrate everything in the database to work with the new version
  shell: |
    cd /var/www/miq/vmdb
    rake db:migrate
    exit 0
- name: resets the ManageIQ
  shell: |
    cd /var/www/miq/vmdb
    rake evm:automate:reset
    exit 0

- name: Restart PostgreSQL
  service:
    name: "{{ ansible_env['APPLIANCE_PG_SERVICE'] }}"
    state: restarted