---
- name: adding cfme upgrade yum repositories
  yum_repository:
    name: "update-{{ item.0 }}"
    description: "CFME upgrade repo #{{ item.0 }}"
    baseurl: "{{ item.1 }}"
    gpgcheck: no
  with_indexed_items: "{{ repos }}"

- name: Register to subscription manager
  redhat_subscription:
    state: present
    username: "{{ username }}"
    password: "{{ password }}"